openapi: 3.0.3
info:
  title: Emergency App - Michalovce
  version: 0.0.0
paths:
  /api/citizen/:
    get:
      operationId: api_citizen_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Citizen'
          description: ''
    post:
      operationId: api_citizen_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Citizen'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Citizen'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Citizen'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Citizen'
          description: ''
  /api/emergencyEvent/:
    get:
      operationId: api_emergencyEvent_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmergencyEvent'
          description: ''
    post:
      operationId: api_emergencyEvent_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmergencyEventReceive'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EmergencyEventReceive'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EmergencyEventReceive'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmergencyEvent'
          description: ''
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Citizen:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        firstName:
          type: string
          maxLength: 100
        lastName:
          type: string
          maxLength: 200
        phoneNumber:
          type: string
          maxLength: 20
      required:
      - firstName
      - id
      - lastName
      - phoneNumber
    EmergencyEvent:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        citizen:
          $ref: '#/components/schemas/Citizen'
        poss:
          type: array
          items:
            $ref: '#/components/schemas/Location'
        createdDateTime:
          type: string
          format: date-time
          readOnly: true
        checked:
          type: boolean
      required:
      - citizen
      - createdDateTime
      - id
      - poss
    EmergencyEventReceive:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        pos:
          type: object
          additionalProperties: {}
        citizenId:
          type: integer
      required:
      - citizenId
      - id
      - pos
    Location:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
      required:
      - id
      - lat
      - lng
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
