# Generated by Django 4.1.7 on 2023-03-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessedTime', models.DateTimeField()),
            ],
        ),
    ]
