# Generated by Django 4.1.7 on 2023-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyEvent', '0003_emergencyevent_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessedTime',
        ),
        migrations.RemoveField(
            model_name='emergencyevent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencyevent',
            name='longitude',
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='pos',
            field=models.TextField(default='[]'),
        ),
    ]
