# Generated by Django 4.1.7 on 2023-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyEvent', '0005_alter_emergencyevent_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyevent',
            name='pos',
            field=models.JSONField(null=True),
        ),
    ]
