# Generated by Django 4.1.7 on 2023-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyEvent', '0006_alter_emergencyevent_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevent',
            name='posArray',
            field=models.TextField(default='[]'),
        ),
    ]
