# Generated by Django 4.1.7 on 2023-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyEvent', '0007_emergencyevent_posarray'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencyevent',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='emergencyevent',
            name='posArray',
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='poss',
            field=models.ManyToManyField(to='emergencyEvent.location'),
        ),
    ]
